//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace happyNumber.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("happyNumber.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500
        ///3 4 6 7 8
        ///2 4 5 7 10
        ///2 6
        ///2 4 5 8
        ///3 5 6 8 9
        ///7 8 9 10
        ///2 3 4 6
        ///6 7 10
        ///2 4 5 7 9
        ///3 5 7 8 10
        ///2 3 5 6 7 8
        ///2 4 5 8 10
        ///2 4 6 7 8 10
        ///3 4
        ///3 5 8 9 10
        ///4 7 10
        ///4 5 6 9 10
        ///2 3 9 10
        ///3 7 9
        ///4 5 6 7 8
        ///5 6 9
        ///4 6 8 10
        ///6 7 9 10
        ///3 4 5 9
        ///2 3 4 6 7 8 10
        ///2 5 8 9
        ///3 7
        ///3 4 5 6 10
        ///6 7 8
        ///3 4 5 6 8 9
        ///4 5 7 8 10
        ///2 3 4 6 7 9 10
        ///4 5 6 10
        ///2 3 5 7 10
        ///5 6 9 10
        ///3 5 6 7 8
        ///2 7 8 10
        ///2 5 7 9 10
        ///3 6 8 9
        ///2 3 7 10
        ///3 5 8
        ///2 4 5 7 8 9
        ///3 7 9 10
        ///2 3 4 6 8
        ///3 4 5 10
        ///2 5 6 7 9
        ///3 6 7 8
        ///2 3
        ///2 3 6 8 10
        ///2 5 6 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string largePractice {
            get {
                return ResourceManager.GetString("largePractice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 42
        ///2 6 8
        ///3 5 7
        ///3 6 9
        ///2 3
        ///7 8 9
        ///2 9 10
        ///6 9
        ///3 8 9
        ///7 10
        ///2 7 8
        ///8 9 10
        ///6 7 10
        ///2 4 5
        ///3 6 7
        ///6 7 8
        ///3 6
        ///2 5
        ///7 8 10
        ///2 4 9
        ///4 10
        ///3 4 7
        ///2 6 10
        ///2 8 9
        ///3 7
        ///2 4 8
        ///3 10
        ///3 9
        ///5 9 10
        ///8 9
        ///4 6 7
        ///4 5 7
        ///5 8 10
        ///2 7 10
        ///2 5 9
        ///3 5 6
        ///6 8 9
        ///3 4 8
        ///3 8
        ///2 7 9
        ///2 5 10
        ///2 7
        ///3 4 5.
        /// </summary>
        internal static string smallPractice {
            get {
                return ResourceManager.GetString("smallPractice", resourceCulture);
            }
        }
    }
}
